// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: log/conf.proto

package log

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
)

// Validate checks the field values on StdoutConf with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *StdoutConf) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Enable

	// no validation rules for Level

	return nil
}

// StdoutConfValidationError is the validation error returned by
// StdoutConf.Validate if the designated constraints aren't met.
type StdoutConfValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e StdoutConfValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e StdoutConfValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e StdoutConfValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e StdoutConfValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e StdoutConfValidationError) ErrorName() string { return "StdoutConfValidationError" }

// Error satisfies the builtin error interface
func (e StdoutConfValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sStdoutConf.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = StdoutConfValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = StdoutConfValidationError{}

// Validate checks the field values on FileConf with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *FileConf) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Enable

	// no validation rules for Level

	// no validation rules for Path

	// no validation rules for Name

	return nil
}

// FileConfValidationError is the validation error returned by
// FileConf.Validate if the designated constraints aren't met.
type FileConfValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e FileConfValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e FileConfValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e FileConfValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e FileConfValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e FileConfValidationError) ErrorName() string { return "FileConfValidationError" }

// Error satisfies the builtin error interface
func (e FileConfValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sFileConf.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = FileConfValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = FileConfValidationError{}

// Validate checks the field values on FluentConf with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *FluentConf) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Enable

	// no validation rules for Level

	// no validation rules for Addr

	return nil
}

// FluentConfValidationError is the validation error returned by
// FluentConf.Validate if the designated constraints aren't met.
type FluentConfValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e FluentConfValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e FluentConfValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e FluentConfValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e FluentConfValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e FluentConfValidationError) ErrorName() string { return "FluentConfValidationError" }

// Error satisfies the builtin error interface
func (e FluentConfValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sFluentConf.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = FluentConfValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = FluentConfValidationError{}

// Validate checks the field values on Conf with the rules defined in the proto
// definition for this message. If any rules are violated, an error is returned.
func (m *Conf) Validate() error {
	if m == nil {
		return nil
	}

	if v, ok := interface{}(m.GetStdout()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ConfValidationError{
				field:  "Stdout",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if v, ok := interface{}(m.GetFile()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ConfValidationError{
				field:  "File",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if v, ok := interface{}(m.GetFluent()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ConfValidationError{
				field:  "Fluent",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// ConfValidationError is the validation error returned by Conf.Validate if the
// designated constraints aren't met.
type ConfValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ConfValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ConfValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ConfValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ConfValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ConfValidationError) ErrorName() string { return "ConfValidationError" }

// Error satisfies the builtin error interface
func (e ConfValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sConf.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ConfValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ConfValidationError{}
