// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v6.31.1
// source: meta/ecode.proto

package meta

import (
	_ "github.com/go-kratos/kratos/v2/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorReason int32

const (
	// 为某个枚举单独设置错误码
	ErrorReason_MD_NOT_FOUND          ErrorReason = 0
	ErrorReason_DP_NOT_FOUND          ErrorReason = 1
	ErrorReason_TOKEN_NOT_FOUND       ErrorReason = 2
	ErrorReason_UA_NOT_FOUND          ErrorReason = 3
	ErrorReason_REMOTE_ADDR_NOT_FOUND ErrorReason = 4
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0: "MD_NOT_FOUND",
		1: "DP_NOT_FOUND",
		2: "TOKEN_NOT_FOUND",
		3: "UA_NOT_FOUND",
		4: "REMOTE_ADDR_NOT_FOUND",
	}
	ErrorReason_value = map[string]int32{
		"MD_NOT_FOUND":          0,
		"DP_NOT_FOUND":          1,
		"TOKEN_NOT_FOUND":       2,
		"UA_NOT_FOUND":          3,
		"REMOTE_ADDR_NOT_FOUND": 4,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_meta_ecode_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_meta_ecode_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_meta_ecode_proto_rawDescGZIP(), []int{0}
}

var File_meta_ecode_proto protoreflect.FileDescriptor

var file_meta_ecode_proto_rawDesc = []byte{
	0x0a, 0x10, 0x6d, 0x65, 0x74, 0x61, 0x2f, 0x65, 0x63, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x1a, 0x13, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73,
	0x2f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2a, 0x79, 0x0a,
	0x0b, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x0c,
	0x4d, 0x44, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x46, 0x4f, 0x55, 0x4e, 0x44, 0x10, 0x00, 0x12, 0x10,
	0x0a, 0x0c, 0x44, 0x50, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x46, 0x4f, 0x55, 0x4e, 0x44, 0x10, 0x01,
	0x12, 0x13, 0x0a, 0x0f, 0x54, 0x4f, 0x4b, 0x45, 0x4e, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x46, 0x4f,
	0x55, 0x4e, 0x44, 0x10, 0x02, 0x12, 0x10, 0x0a, 0x0c, 0x55, 0x41, 0x5f, 0x4e, 0x4f, 0x54, 0x5f,
	0x46, 0x4f, 0x55, 0x4e, 0x44, 0x10, 0x03, 0x12, 0x19, 0x0a, 0x15, 0x52, 0x45, 0x4d, 0x4f, 0x54,
	0x45, 0x5f, 0x41, 0x44, 0x44, 0x52, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x46, 0x4f, 0x55, 0x4e, 0x44,
	0x10, 0x04, 0x1a, 0x04, 0xa0, 0x45, 0xf4, 0x03, 0x42, 0x24, 0x5a, 0x22, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x6f, 0x2d, 0x62, 0x61, 0x6d, 0x62, 0x6f, 0x6f,
	0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x3b, 0x6d, 0x65, 0x74, 0x61, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_meta_ecode_proto_rawDescOnce sync.Once
	file_meta_ecode_proto_rawDescData = file_meta_ecode_proto_rawDesc
)

func file_meta_ecode_proto_rawDescGZIP() []byte {
	file_meta_ecode_proto_rawDescOnce.Do(func() {
		file_meta_ecode_proto_rawDescData = protoimpl.X.CompressGZIP(file_meta_ecode_proto_rawDescData)
	})
	return file_meta_ecode_proto_rawDescData
}

var file_meta_ecode_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_meta_ecode_proto_goTypes = []interface{}{
	(ErrorReason)(0), // 0: meta.ErrorReason
}
var file_meta_ecode_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_meta_ecode_proto_init() }
func file_meta_ecode_proto_init() {
	if File_meta_ecode_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_meta_ecode_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_meta_ecode_proto_goTypes,
		DependencyIndexes: file_meta_ecode_proto_depIdxs,
		EnumInfos:         file_meta_ecode_proto_enumTypes,
	}.Build()
	File_meta_ecode_proto = out.File
	file_meta_ecode_proto_rawDesc = nil
	file_meta_ecode_proto_goTypes = nil
	file_meta_ecode_proto_depIdxs = nil
}
