// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package meta

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

// 为某个枚举单独设置错误码
func IsMdNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_MD_NOT_FOUND.String() && e.Code == 500
}

// 为某个枚举单独设置错误码
func ErrorMdNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_MD_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}

func IsDpNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_DP_NOT_FOUND.String() && e.Code == 500
}

func ErrorDpNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_DP_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}

func IsTokenNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_TOKEN_NOT_FOUND.String() && e.Code == 500
}

func ErrorTokenNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_TOKEN_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}

func IsUaNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_UA_NOT_FOUND.String() && e.Code == 500
}

func ErrorUaNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_UA_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}

func IsRemoteAddrNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_REMOTE_ADDR_NOT_FOUND.String() && e.Code == 500
}

func ErrorRemoteAddrNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_REMOTE_ADDR_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}
