// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v6.31.1
// source: queue/rabbitmq/ecode.proto

package rabbitmq

import (
	_ "github.com/go-kratos/kratos/v2/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorReason int32

const (
	ErrorReason_UNKOWN         ErrorReason = 0
	ErrorReason_DISCONNECT     ErrorReason = 1 // 断链接了
	ErrorReason_CHANNEL_CLOSED ErrorReason = 2 // channel 断了
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0: "UNKOWN",
		1: "DISCONNECT",
		2: "CHANNEL_CLOSED",
	}
	ErrorReason_value = map[string]int32{
		"UNKOWN":         0,
		"DISCONNECT":     1,
		"CHANNEL_CLOSED": 2,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_queue_rabbitmq_ecode_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_queue_rabbitmq_ecode_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_queue_rabbitmq_ecode_proto_rawDescGZIP(), []int{0}
}

var File_queue_rabbitmq_ecode_proto protoreflect.FileDescriptor

var file_queue_rabbitmq_ecode_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x71, 0x75, 0x65, 0x75, 0x65, 0x2f, 0x72, 0x61, 0x62, 0x62, 0x69, 0x74, 0x6d, 0x71,
	0x2f, 0x65, 0x63, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x71, 0x75,
	0x65, 0x75, 0x65, 0x2e, 0x72, 0x61, 0x62, 0x62, 0x69, 0x74, 0x6d, 0x71, 0x1a, 0x13, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x73, 0x2f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2a, 0x43, 0x0a, 0x0b, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e,
	0x12, 0x0a, 0x0a, 0x06, 0x55, 0x4e, 0x4b, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a,
	0x44, 0x49, 0x53, 0x43, 0x4f, 0x4e, 0x4e, 0x45, 0x43, 0x54, 0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e,
	0x43, 0x48, 0x41, 0x4e, 0x4e, 0x45, 0x4c, 0x5f, 0x43, 0x4c, 0x4f, 0x53, 0x45, 0x44, 0x10, 0x02,
	0x1a, 0x04, 0xa0, 0x45, 0xf4, 0x03, 0x42, 0x32, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x6f, 0x2d, 0x62, 0x61, 0x6d, 0x62, 0x6f, 0x6f, 0x2f, 0x70,
	0x6b, 0x67, 0x2f, 0x71, 0x75, 0x65, 0x75, 0x65, 0x2f, 0x72, 0x61, 0x62, 0x62, 0x69, 0x74, 0x6d,
	0x71, 0x3b, 0x72, 0x61, 0x62, 0x62, 0x69, 0x74, 0x6d, 0x71, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_queue_rabbitmq_ecode_proto_rawDescOnce sync.Once
	file_queue_rabbitmq_ecode_proto_rawDescData = file_queue_rabbitmq_ecode_proto_rawDesc
)

func file_queue_rabbitmq_ecode_proto_rawDescGZIP() []byte {
	file_queue_rabbitmq_ecode_proto_rawDescOnce.Do(func() {
		file_queue_rabbitmq_ecode_proto_rawDescData = protoimpl.X.CompressGZIP(file_queue_rabbitmq_ecode_proto_rawDescData)
	})
	return file_queue_rabbitmq_ecode_proto_rawDescData
}

var file_queue_rabbitmq_ecode_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_queue_rabbitmq_ecode_proto_goTypes = []interface{}{
	(ErrorReason)(0), // 0: queue.rabbitmq.ErrorReason
}
var file_queue_rabbitmq_ecode_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_queue_rabbitmq_ecode_proto_init() }
func file_queue_rabbitmq_ecode_proto_init() {
	if File_queue_rabbitmq_ecode_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_queue_rabbitmq_ecode_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_queue_rabbitmq_ecode_proto_goTypes,
		DependencyIndexes: file_queue_rabbitmq_ecode_proto_depIdxs,
		EnumInfos:         file_queue_rabbitmq_ecode_proto_enumTypes,
	}.Build()
	File_queue_rabbitmq_ecode_proto = out.File
	file_queue_rabbitmq_ecode_proto_rawDesc = nil
	file_queue_rabbitmq_ecode_proto_goTypes = nil
	file_queue_rabbitmq_ecode_proto_depIdxs = nil
}
