// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: client/kafka/conf.proto

package kafka

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
)

// Validate checks the field values on Net with the rules defined in the proto
// definition for this message. If any rules are violated, an error is returned.
func (m *Net) Validate() error {
	if m == nil {
		return nil
	}

	if v, ok := interface{}(m.GetSasl()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return NetValidationError{
				field:  "Sasl",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if v, ok := interface{}(m.GetTls()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return NetValidationError{
				field:  "Tls",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// NetValidationError is the validation error returned by Net.Validate if the
// designated constraints aren't met.
type NetValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e NetValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e NetValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e NetValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e NetValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e NetValidationError) ErrorName() string { return "NetValidationError" }

// Error satisfies the builtin error interface
func (e NetValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sNet.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = NetValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = NetValidationError{}

// Validate checks the field values on Conf with the rules defined in the proto
// definition for this message. If any rules are violated, an error is returned.
func (m *Conf) Validate() error {
	if m == nil {
		return nil
	}

	if v, ok := interface{}(m.GetNet()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ConfValidationError{
				field:  "Net",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Topic

	// no validation rules for Group

	if v, ok := interface{}(m.GetReadTimeout()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ConfValidationError{
				field:  "ReadTimeout",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if v, ok := interface{}(m.GetWriteTimeout()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ConfValidationError{
				field:  "WriteTimeout",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Acks

	return nil
}

// ConfValidationError is the validation error returned by Conf.Validate if the
// designated constraints aren't met.
type ConfValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ConfValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ConfValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ConfValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ConfValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ConfValidationError) ErrorName() string { return "ConfValidationError" }

// Error satisfies the builtin error interface
func (e ConfValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sConf.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ConfValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ConfValidationError{}

// Validate checks the field values on Net_SASL with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *Net_SASL) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Enable

	// no validation rules for User

	// no validation rules for Password

	return nil
}

// Net_SASLValidationError is the validation error returned by
// Net_SASL.Validate if the designated constraints aren't met.
type Net_SASLValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e Net_SASLValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e Net_SASLValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e Net_SASLValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e Net_SASLValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e Net_SASLValidationError) ErrorName() string { return "Net_SASLValidationError" }

// Error satisfies the builtin error interface
func (e Net_SASLValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sNet_SASL.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = Net_SASLValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = Net_SASLValidationError{}

// Validate checks the field values on Net_TLS with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *Net_TLS) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Enable

	// no validation rules for RootCa

	// no validation rules for Jks

	// no validation rules for Password

	// no validation rules for Cert

	// no validation rules for Key

	return nil
}

// Net_TLSValidationError is the validation error returned by Net_TLS.Validate
// if the designated constraints aren't met.
type Net_TLSValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e Net_TLSValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e Net_TLSValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e Net_TLSValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e Net_TLSValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e Net_TLSValidationError) ErrorName() string { return "Net_TLSValidationError" }

// Error satisfies the builtin error interface
func (e Net_TLSValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sNet_TLS.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = Net_TLSValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = Net_TLSValidationError{}
