// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: store/gormx/conf.proto

package gormx

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// dbMySQL Gorm Drivers mysql || postgres || sqlite || sqlserver
type DBType int32

const (
	DBType_UNKNOWN   DBType = 0
	DBType_mysql     DBType = 1
	DBType_postgres  DBType = 2
	DBType_sqlite    DBType = 3
	DBType_sqlserver DBType = 4
)

// Enum value maps for DBType.
var (
	DBType_name = map[int32]string{
		0: "UNKNOWN",
		1: "mysql",
		2: "postgres",
		3: "sqlite",
		4: "sqlserver",
	}
	DBType_value = map[string]int32{
		"UNKNOWN":   0,
		"mysql":     1,
		"postgres":  2,
		"sqlite":    3,
		"sqlserver": 4,
	}
)

func (x DBType) Enum() *DBType {
	p := new(DBType)
	*p = x
	return p
}

func (x DBType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DBType) Descriptor() protoreflect.EnumDescriptor {
	return file_store_gormx_conf_proto_enumTypes[0].Descriptor()
}

func (DBType) Type() protoreflect.EnumType {
	return &file_store_gormx_conf_proto_enumTypes[0]
}

func (x DBType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DBType.Descriptor instead.
func (DBType) EnumDescriptor() ([]byte, []int) {
	return file_store_gormx_conf_proto_rawDescGZIP(), []int{0}
}

type Conf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Driver          DBType               `protobuf:"varint,1,opt,name=driver,proto3,enum=store.gormx.DBType" json:"driver,omitempty"`
	Source          string               `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	LogLevel        int32                `protobuf:"varint,3,opt,name=logLevel,proto3" json:"logLevel,omitempty"`
	MaxOpenConns    int32                `protobuf:"varint,4,opt,name=maxOpenConns,proto3" json:"maxOpenConns,omitempty"`
	MaxIdleConns    int32                `protobuf:"varint,5,opt,name=maxIdleConns,proto3" json:"maxIdleConns,omitempty"`
	ConnMaxLifetime *durationpb.Duration `protobuf:"bytes,6,opt,name=connMaxLifetime,proto3" json:"connMaxLifetime,omitempty"`
}

func (x *Conf) Reset() {
	*x = Conf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_store_gormx_conf_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Conf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Conf) ProtoMessage() {}

func (x *Conf) ProtoReflect() protoreflect.Message {
	mi := &file_store_gormx_conf_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Conf.ProtoReflect.Descriptor instead.
func (*Conf) Descriptor() ([]byte, []int) {
	return file_store_gormx_conf_proto_rawDescGZIP(), []int{0}
}

func (x *Conf) GetDriver() DBType {
	if x != nil {
		return x.Driver
	}
	return DBType_UNKNOWN
}

func (x *Conf) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Conf) GetLogLevel() int32 {
	if x != nil {
		return x.LogLevel
	}
	return 0
}

func (x *Conf) GetMaxOpenConns() int32 {
	if x != nil {
		return x.MaxOpenConns
	}
	return 0
}

func (x *Conf) GetMaxIdleConns() int32 {
	if x != nil {
		return x.MaxIdleConns
	}
	return 0
}

func (x *Conf) GetConnMaxLifetime() *durationpb.Duration {
	if x != nil {
		return x.ConnMaxLifetime
	}
	return nil
}

var File_store_gormx_conf_proto protoreflect.FileDescriptor

var file_store_gormx_conf_proto_rawDesc = []byte{
	0x0a, 0x16, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2f, 0x67, 0x6f, 0x72, 0x6d, 0x78, 0x2f, 0x63, 0x6f,
	0x6e, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e,
	0x67, 0x6f, 0x72, 0x6d, 0x78, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xf4, 0x01, 0x0a, 0x04, 0x43, 0x6f, 0x6e, 0x66, 0x12, 0x2b,
	0x0a, 0x06, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13,
	0x2e, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x67, 0x6f, 0x72, 0x6d, 0x78, 0x2e, 0x44, 0x42, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x06, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x6f, 0x67, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6c, 0x6f, 0x67, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12,
	0x22, 0x0a, 0x0c, 0x6d, 0x61, 0x78, 0x4f, 0x70, 0x65, 0x6e, 0x43, 0x6f, 0x6e, 0x6e, 0x73, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x6d, 0x61, 0x78, 0x4f, 0x70, 0x65, 0x6e, 0x43, 0x6f,
	0x6e, 0x6e, 0x73, 0x12, 0x22, 0x0a, 0x0c, 0x6d, 0x61, 0x78, 0x49, 0x64, 0x6c, 0x65, 0x43, 0x6f,
	0x6e, 0x6e, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x6d, 0x61, 0x78, 0x49, 0x64,
	0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x6e, 0x73, 0x12, 0x43, 0x0a, 0x0f, 0x63, 0x6f, 0x6e, 0x6e, 0x4d,
	0x61, 0x78, 0x4c, 0x69, 0x66, 0x65, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x19, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0f, 0x63, 0x6f, 0x6e,
	0x6e, 0x4d, 0x61, 0x78, 0x4c, 0x69, 0x66, 0x65, 0x74, 0x69, 0x6d, 0x65, 0x2a, 0x49, 0x0a, 0x06,
	0x44, 0x42, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57,
	0x4e, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x6d, 0x79, 0x73, 0x71, 0x6c, 0x10, 0x01, 0x12, 0x0c,
	0x0a, 0x08, 0x70, 0x6f, 0x73, 0x74, 0x67, 0x72, 0x65, 0x73, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06,
	0x73, 0x71, 0x6c, 0x69, 0x74, 0x65, 0x10, 0x03, 0x12, 0x0d, 0x0a, 0x09, 0x73, 0x71, 0x6c, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x10, 0x04, 0x42, 0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x6f, 0x2d, 0x62, 0x61, 0x6d, 0x62, 0x6f, 0x6f, 0x2f,
	0x70, 0x6b, 0x67, 0x2f, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2f, 0x67, 0x6f, 0x72, 0x6d, 0x78, 0x3b,
	0x67, 0x6f, 0x72, 0x6d, 0x78, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_store_gormx_conf_proto_rawDescOnce sync.Once
	file_store_gormx_conf_proto_rawDescData = file_store_gormx_conf_proto_rawDesc
)

func file_store_gormx_conf_proto_rawDescGZIP() []byte {
	file_store_gormx_conf_proto_rawDescOnce.Do(func() {
		file_store_gormx_conf_proto_rawDescData = protoimpl.X.CompressGZIP(file_store_gormx_conf_proto_rawDescData)
	})
	return file_store_gormx_conf_proto_rawDescData
}

var file_store_gormx_conf_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_store_gormx_conf_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_store_gormx_conf_proto_goTypes = []interface{}{
	(DBType)(0),                 // 0: store.gormx.DBType
	(*Conf)(nil),                // 1: store.gormx.Conf
	(*durationpb.Duration)(nil), // 2: google.protobuf.Duration
}
var file_store_gormx_conf_proto_depIdxs = []int32{
	0, // 0: store.gormx.Conf.driver:type_name -> store.gormx.DBType
	2, // 1: store.gormx.Conf.connMaxLifetime:type_name -> google.protobuf.Duration
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_store_gormx_conf_proto_init() }
func file_store_gormx_conf_proto_init() {
	if File_store_gormx_conf_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_store_gormx_conf_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Conf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_store_gormx_conf_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_store_gormx_conf_proto_goTypes,
		DependencyIndexes: file_store_gormx_conf_proto_depIdxs,
		EnumInfos:         file_store_gormx_conf_proto_enumTypes,
		MessageInfos:      file_store_gormx_conf_proto_msgTypes,
	}.Build()
	File_store_gormx_conf_proto = out.File
	file_store_gormx_conf_proto_rawDesc = nil
	file_store_gormx_conf_proto_goTypes = nil
	file_store_gormx_conf_proto_depIdxs = nil
}
