// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v5.27.1
// source: otel/conf.proto

package otel

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProviderType int32

const (
	ProviderType_Unkown     ProviderType = 0
	ProviderType_Jaeger     ProviderType = 1
	ProviderType_Stdout     ProviderType = 2
	ProviderType_Otlp       ProviderType = 3
	ProviderType_Prometheus ProviderType = 4
	ProviderType_Zipkin     ProviderType = 5
)

// Enum value maps for ProviderType.
var (
	ProviderType_name = map[int32]string{
		0: "Unkown",
		1: "Jaeger",
		2: "Stdout",
		3: "Otlp",
		4: "Prometheus",
		5: "Zipkin",
	}
	ProviderType_value = map[string]int32{
		"Unkown":     0,
		"Jaeger":     1,
		"Stdout":     2,
		"Otlp":       3,
		"Prometheus": 4,
		"Zipkin":     5,
	}
)

func (x ProviderType) Enum() *ProviderType {
	p := new(ProviderType)
	*p = x
	return p
}

func (x ProviderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProviderType) Descriptor() protoreflect.EnumDescriptor {
	return file_otel_conf_proto_enumTypes[0].Descriptor()
}

func (ProviderType) Type() protoreflect.EnumType {
	return &file_otel_conf_proto_enumTypes[0]
}

func (x ProviderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProviderType.Descriptor instead.
func (ProviderType) EnumDescriptor() ([]byte, []int) {
	return file_otel_conf_proto_rawDescGZIP(), []int{0}
}

type Type int32

const (
	Type_Unkown1 Type = 0
	Type_Traces  Type = 1
	Type_Metrics Type = 2
)

// Enum value maps for Type.
var (
	Type_name = map[int32]string{
		0: "Unkown1",
		1: "Traces",
		2: "Metrics",
	}
	Type_value = map[string]int32{
		"Unkown1": 0,
		"Traces":  1,
		"Metrics": 2,
	}
)

func (x Type) Enum() *Type {
	p := new(Type)
	*p = x
	return p
}

func (x Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Type) Descriptor() protoreflect.EnumDescriptor {
	return file_otel_conf_proto_enumTypes[1].Descriptor()
}

func (Type) Type() protoreflect.EnumType {
	return &file_otel_conf_proto_enumTypes[1]
}

func (x Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Type.Descriptor instead.
func (Type) EnumDescriptor() ([]byte, []int) {
	return file_otel_conf_proto_rawDescGZIP(), []int{1}
}

type Conf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProviderType ProviderType `protobuf:"varint,1,opt,name=providerType,proto3,enum=otel.ProviderType" json:"providerType,omitempty"`
	Type         Type         `protobuf:"varint,2,opt,name=type,proto3,enum=otel.Type" json:"type,omitempty"`
	Endpoint     string       `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Xray         bool         `protobuf:"varint,5,opt,name=xray,proto3" json:"xray,omitempty"`
	GrpcToken    string       `protobuf:"bytes,6,opt,name=grpcToken,proto3" json:"grpcToken,omitempty"`
	Environment  string       `protobuf:"bytes,7,opt,name=environment,proto3" json:"environment,omitempty"`
}

func (x *Conf) Reset() {
	*x = Conf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_otel_conf_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Conf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Conf) ProtoMessage() {}

func (x *Conf) ProtoReflect() protoreflect.Message {
	mi := &file_otel_conf_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Conf.ProtoReflect.Descriptor instead.
func (*Conf) Descriptor() ([]byte, []int) {
	return file_otel_conf_proto_rawDescGZIP(), []int{0}
}

func (x *Conf) GetProviderType() ProviderType {
	if x != nil {
		return x.ProviderType
	}
	return ProviderType_Unkown
}

func (x *Conf) GetType() Type {
	if x != nil {
		return x.Type
	}
	return Type_Unkown1
}

func (x *Conf) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *Conf) GetXray() bool {
	if x != nil {
		return x.Xray
	}
	return false
}

func (x *Conf) GetGrpcToken() string {
	if x != nil {
		return x.GrpcToken
	}
	return ""
}

func (x *Conf) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

var File_otel_conf_proto protoreflect.FileDescriptor

var file_otel_conf_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x6f, 0x74, 0x65, 0x6c, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x04, 0x6f, 0x74, 0x65, 0x6c, 0x22, 0xce, 0x01, 0x0a, 0x04, 0x43, 0x6f, 0x6e, 0x66,
	0x12, 0x36, 0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x6f, 0x74, 0x65, 0x6c, 0x2e, 0x50, 0x72,
	0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0c, 0x70, 0x72, 0x6f, 0x76,
	0x69, 0x64, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1e, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0a, 0x2e, 0x6f, 0x74, 0x65, 0x6c, 0x2e, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x70,
	0x6f, 0x69, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x6e, 0x64, 0x70,
	0x6f, 0x69, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x78, 0x72, 0x61, 0x79, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x04, 0x78, 0x72, 0x61, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x67, 0x72, 0x70, 0x63,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x67, 0x72, 0x70,
	0x63, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x65, 0x6e, 0x76, 0x69, 0x72, 0x6f,
	0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x65, 0x6e, 0x76,
	0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x2a, 0x58, 0x0a, 0x0c, 0x50, 0x72, 0x6f, 0x76,
	0x69, 0x64, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x55, 0x6e, 0x6b, 0x6f,
	0x77, 0x6e, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x4a, 0x61, 0x65, 0x67, 0x65, 0x72, 0x10, 0x01,
	0x12, 0x0a, 0x0a, 0x06, 0x53, 0x74, 0x64, 0x6f, 0x75, 0x74, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04,
	0x4f, 0x74, 0x6c, 0x70, 0x10, 0x03, 0x12, 0x0e, 0x0a, 0x0a, 0x50, 0x72, 0x6f, 0x6d, 0x65, 0x74,
	0x68, 0x65, 0x75, 0x73, 0x10, 0x04, 0x12, 0x0a, 0x0a, 0x06, 0x5a, 0x69, 0x70, 0x6b, 0x69, 0x6e,
	0x10, 0x05, 0x2a, 0x2c, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x6e,
	0x6b, 0x6f, 0x77, 0x6e, 0x31, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x54, 0x72, 0x61, 0x63, 0x65,
	0x73, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x10, 0x02,
	0x42, 0x24, 0x5a, 0x22, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67,
	0x6f, 0x2d, 0x62, 0x61, 0x6d, 0x62, 0x6f, 0x6f, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x6f, 0x74, 0x65,
	0x6c, 0x3b, 0x6f, 0x74, 0x65, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_otel_conf_proto_rawDescOnce sync.Once
	file_otel_conf_proto_rawDescData = file_otel_conf_proto_rawDesc
)

func file_otel_conf_proto_rawDescGZIP() []byte {
	file_otel_conf_proto_rawDescOnce.Do(func() {
		file_otel_conf_proto_rawDescData = protoimpl.X.CompressGZIP(file_otel_conf_proto_rawDescData)
	})
	return file_otel_conf_proto_rawDescData
}

var file_otel_conf_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_otel_conf_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_otel_conf_proto_goTypes = []interface{}{
	(ProviderType)(0), // 0: otel.ProviderType
	(Type)(0),         // 1: otel.Type
	(*Conf)(nil),      // 2: otel.Conf
}
var file_otel_conf_proto_depIdxs = []int32{
	0, // 0: otel.Conf.providerType:type_name -> otel.ProviderType
	1, // 1: otel.Conf.type:type_name -> otel.Type
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_otel_conf_proto_init() }
func file_otel_conf_proto_init() {
	if File_otel_conf_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_otel_conf_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Conf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_otel_conf_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_otel_conf_proto_goTypes,
		DependencyIndexes: file_otel_conf_proto_depIdxs,
		EnumInfos:         file_otel_conf_proto_enumTypes,
		MessageInfos:      file_otel_conf_proto_msgTypes,
	}.Build()
	File_otel_conf_proto = out.File
	file_otel_conf_proto_rawDesc = nil
	file_otel_conf_proto_goTypes = nil
	file_otel_conf_proto_depIdxs = nil
}
