// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: otel/conf.proto

package otel

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Jaeger struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Enable   bool   `protobuf:"varint,1,opt,name=enable,proto3" json:"enable,omitempty"`
	Endpoint string `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Metrics  bool   `protobuf:"varint,3,opt,name=metrics,proto3" json:"metrics,omitempty"`
	Traces   bool   `protobuf:"varint,4,opt,name=traces,proto3" json:"traces,omitempty"`
}

func (x *Jaeger) Reset() {
	*x = Jaeger{}
	if protoimpl.UnsafeEnabled {
		mi := &file_otel_conf_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Jaeger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Jaeger) ProtoMessage() {}

func (x *Jaeger) ProtoReflect() protoreflect.Message {
	mi := &file_otel_conf_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Jaeger.ProtoReflect.Descriptor instead.
func (*Jaeger) Descriptor() ([]byte, []int) {
	return file_otel_conf_proto_rawDescGZIP(), []int{0}
}

func (x *Jaeger) GetEnable() bool {
	if x != nil {
		return x.Enable
	}
	return false
}

func (x *Jaeger) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *Jaeger) GetMetrics() bool {
	if x != nil {
		return x.Metrics
	}
	return false
}

func (x *Jaeger) GetTraces() bool {
	if x != nil {
		return x.Traces
	}
	return false
}

type Stdout struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Enable       bool   `protobuf:"varint,1,opt,name=enable,proto3" json:"enable,omitempty"`
	Traces       bool   `protobuf:"varint,2,opt,name=traces,proto3" json:"traces,omitempty"`
	TraceOutput  string `protobuf:"bytes,3,opt,name=trace_output,json=traceOutput,proto3" json:"trace_output,omitempty"`
	Metrics      bool   `protobuf:"varint,4,opt,name=metrics,proto3" json:"metrics,omitempty"`
	MetricOutput string `protobuf:"bytes,5,opt,name=metric_output,json=metricOutput,proto3" json:"metric_output,omitempty"`
}

func (x *Stdout) Reset() {
	*x = Stdout{}
	if protoimpl.UnsafeEnabled {
		mi := &file_otel_conf_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Stdout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stdout) ProtoMessage() {}

func (x *Stdout) ProtoReflect() protoreflect.Message {
	mi := &file_otel_conf_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stdout.ProtoReflect.Descriptor instead.
func (*Stdout) Descriptor() ([]byte, []int) {
	return file_otel_conf_proto_rawDescGZIP(), []int{1}
}

func (x *Stdout) GetEnable() bool {
	if x != nil {
		return x.Enable
	}
	return false
}

func (x *Stdout) GetTraces() bool {
	if x != nil {
		return x.Traces
	}
	return false
}

func (x *Stdout) GetTraceOutput() string {
	if x != nil {
		return x.TraceOutput
	}
	return ""
}

func (x *Stdout) GetMetrics() bool {
	if x != nil {
		return x.Metrics
	}
	return false
}

func (x *Stdout) GetMetricOutput() string {
	if x != nil {
		return x.MetricOutput
	}
	return ""
}

type Otlp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Enable   bool   `protobuf:"varint,1,opt,name=enable,proto3" json:"enable,omitempty"`
	Endpoint string `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Metrics  bool   `protobuf:"varint,3,opt,name=metrics,proto3" json:"metrics,omitempty"`
	Traces   bool   `protobuf:"varint,4,opt,name=traces,proto3" json:"traces,omitempty"`
	Xray     bool   `protobuf:"varint,5,opt,name=xray,proto3" json:"xray,omitempty"`
}

func (x *Otlp) Reset() {
	*x = Otlp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_otel_conf_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Otlp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Otlp) ProtoMessage() {}

func (x *Otlp) ProtoReflect() protoreflect.Message {
	mi := &file_otel_conf_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Otlp.ProtoReflect.Descriptor instead.
func (*Otlp) Descriptor() ([]byte, []int) {
	return file_otel_conf_proto_rawDescGZIP(), []int{2}
}

func (x *Otlp) GetEnable() bool {
	if x != nil {
		return x.Enable
	}
	return false
}

func (x *Otlp) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *Otlp) GetMetrics() bool {
	if x != nil {
		return x.Metrics
	}
	return false
}

func (x *Otlp) GetTraces() bool {
	if x != nil {
		return x.Traces
	}
	return false
}

func (x *Otlp) GetXray() bool {
	if x != nil {
		return x.Xray
	}
	return false
}

type Prometheus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Enable  bool `protobuf:"varint,1,opt,name=enable,proto3" json:"enable,omitempty"`
	Metrics bool `protobuf:"varint,2,opt,name=metrics,proto3" json:"metrics,omitempty"`
}

func (x *Prometheus) Reset() {
	*x = Prometheus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_otel_conf_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Prometheus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Prometheus) ProtoMessage() {}

func (x *Prometheus) ProtoReflect() protoreflect.Message {
	mi := &file_otel_conf_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Prometheus.ProtoReflect.Descriptor instead.
func (*Prometheus) Descriptor() ([]byte, []int) {
	return file_otel_conf_proto_rawDescGZIP(), []int{3}
}

func (x *Prometheus) GetEnable() bool {
	if x != nil {
		return x.Enable
	}
	return false
}

func (x *Prometheus) GetMetrics() bool {
	if x != nil {
		return x.Metrics
	}
	return false
}

type Conf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Jaeger *Jaeger     `protobuf:"bytes,1,opt,name=jaeger,proto3" json:"jaeger,omitempty"`
	Stdout *Stdout     `protobuf:"bytes,2,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Otlp   *Otlp       `protobuf:"bytes,3,opt,name=otlp,proto3" json:"otlp,omitempty"`
	Prom   *Prometheus `protobuf:"bytes,4,opt,name=prom,proto3" json:"prom,omitempty"`
}

func (x *Conf) Reset() {
	*x = Conf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_otel_conf_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Conf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Conf) ProtoMessage() {}

func (x *Conf) ProtoReflect() protoreflect.Message {
	mi := &file_otel_conf_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Conf.ProtoReflect.Descriptor instead.
func (*Conf) Descriptor() ([]byte, []int) {
	return file_otel_conf_proto_rawDescGZIP(), []int{4}
}

func (x *Conf) GetJaeger() *Jaeger {
	if x != nil {
		return x.Jaeger
	}
	return nil
}

func (x *Conf) GetStdout() *Stdout {
	if x != nil {
		return x.Stdout
	}
	return nil
}

func (x *Conf) GetOtlp() *Otlp {
	if x != nil {
		return x.Otlp
	}
	return nil
}

func (x *Conf) GetProm() *Prometheus {
	if x != nil {
		return x.Prom
	}
	return nil
}

var File_otel_conf_proto protoreflect.FileDescriptor

var file_otel_conf_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x6f, 0x74, 0x65, 0x6c, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x04, 0x6f, 0x74, 0x65, 0x6c, 0x22, 0x6e, 0x0a, 0x06, 0x4a, 0x61, 0x65, 0x67, 0x65,
	0x72, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x06, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x6e, 0x64,
	0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x6e, 0x64,
	0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x12,
	0x16, 0x0a, 0x06, 0x74, 0x72, 0x61, 0x63, 0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x06, 0x74, 0x72, 0x61, 0x63, 0x65, 0x73, 0x22, 0x9a, 0x01, 0x0a, 0x06, 0x53, 0x74, 0x64, 0x6f,
	0x75, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x06, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x72,
	0x61, 0x63, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x74, 0x72, 0x61, 0x63,
	0x65, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x74, 0x72, 0x61, 0x63, 0x65, 0x5f, 0x6f, 0x75, 0x74, 0x70,
	0x75, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x74, 0x72, 0x61, 0x63, 0x65, 0x4f,
	0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x12,
	0x23, 0x0a, 0x0d, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x5f, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x4f, 0x75,
	0x74, 0x70, 0x75, 0x74, 0x22, 0x80, 0x01, 0x0a, 0x04, 0x4f, 0x74, 0x6c, 0x70, 0x12, 0x16, 0x0a,
	0x06, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x65,
	0x6e, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e,
	0x74, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x07, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x74,
	0x72, 0x61, 0x63, 0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x74, 0x72, 0x61,
	0x63, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x78, 0x72, 0x61, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x04, 0x78, 0x72, 0x61, 0x79, 0x22, 0x3e, 0x0a, 0x0a, 0x50, 0x72, 0x6f, 0x6d, 0x65,
	0x74, 0x68, 0x65, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x22, 0x98, 0x01, 0x0a, 0x04, 0x43, 0x6f, 0x6e, 0x66,
	0x12, 0x24, 0x0a, 0x06, 0x6a, 0x61, 0x65, 0x67, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0c, 0x2e, 0x6f, 0x74, 0x65, 0x6c, 0x2e, 0x4a, 0x61, 0x65, 0x67, 0x65, 0x72, 0x52, 0x06,
	0x6a, 0x61, 0x65, 0x67, 0x65, 0x72, 0x12, 0x24, 0x0a, 0x06, 0x73, 0x74, 0x64, 0x6f, 0x75, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6f, 0x74, 0x65, 0x6c, 0x2e, 0x53, 0x74,
	0x64, 0x6f, 0x75, 0x74, 0x52, 0x06, 0x73, 0x74, 0x64, 0x6f, 0x75, 0x74, 0x12, 0x1e, 0x0a, 0x04,
	0x6f, 0x74, 0x6c, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x6f, 0x74, 0x65,
	0x6c, 0x2e, 0x4f, 0x74, 0x6c, 0x70, 0x52, 0x04, 0x6f, 0x74, 0x6c, 0x70, 0x12, 0x24, 0x0a, 0x04,
	0x70, 0x72, 0x6f, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6f, 0x74, 0x65,
	0x6c, 0x2e, 0x50, 0x72, 0x6f, 0x6d, 0x65, 0x74, 0x68, 0x65, 0x75, 0x73, 0x52, 0x04, 0x70, 0x72,
	0x6f, 0x6d, 0x42, 0x24, 0x5a, 0x22, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x67, 0x6f, 0x2d, 0x62, 0x61, 0x6d, 0x62, 0x6f, 0x6f, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x6f,
	0x74, 0x65, 0x6c, 0x3b, 0x6f, 0x74, 0x65, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_otel_conf_proto_rawDescOnce sync.Once
	file_otel_conf_proto_rawDescData = file_otel_conf_proto_rawDesc
)

func file_otel_conf_proto_rawDescGZIP() []byte {
	file_otel_conf_proto_rawDescOnce.Do(func() {
		file_otel_conf_proto_rawDescData = protoimpl.X.CompressGZIP(file_otel_conf_proto_rawDescData)
	})
	return file_otel_conf_proto_rawDescData
}

var file_otel_conf_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_otel_conf_proto_goTypes = []interface{}{
	(*Jaeger)(nil),     // 0: otel.Jaeger
	(*Stdout)(nil),     // 1: otel.Stdout
	(*Otlp)(nil),       // 2: otel.Otlp
	(*Prometheus)(nil), // 3: otel.Prometheus
	(*Conf)(nil),       // 4: otel.Conf
}
var file_otel_conf_proto_depIdxs = []int32{
	0, // 0: otel.Conf.jaeger:type_name -> otel.Jaeger
	1, // 1: otel.Conf.stdout:type_name -> otel.Stdout
	2, // 2: otel.Conf.otlp:type_name -> otel.Otlp
	3, // 3: otel.Conf.prom:type_name -> otel.Prometheus
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_otel_conf_proto_init() }
func file_otel_conf_proto_init() {
	if File_otel_conf_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_otel_conf_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Jaeger); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_otel_conf_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Stdout); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_otel_conf_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Otlp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_otel_conf_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Prometheus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_otel_conf_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Conf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_otel_conf_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_otel_conf_proto_goTypes,
		DependencyIndexes: file_otel_conf_proto_depIdxs,
		MessageInfos:      file_otel_conf_proto_msgTypes,
	}.Build()
	File_otel_conf_proto = out.File
	file_otel_conf_proto_rawDesc = nil
	file_otel_conf_proto_goTypes = nil
	file_otel_conf_proto_depIdxs = nil
}
